In [1]:
import numpy as np

### Creating a multilayer perceptron 

In [2]:
a = np.array([[1,1,1,],[1,1,1,],[1,1,1,],[1,1,1,], ])
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
b  = np.array([[1], [1], [1]])
b

array([[1],
       [1],
       [1]])

In [7]:
c = np.dot(a,b)
c

array([[3],
       [3],
       [3],
       [3]])

class NeuralNet():
    def input_layer(self, units, hidden_layer):
        


In [8]:
class NeuralNet():
    def __init__(self):
        self.list_of_all_weights = [] #W
        self.list_of_all_weighted_sum = [] #Z
        self.list_of_all_activations = [] #A

        self.list_of_all_change_in_activations = [] #dZ
        self.list_of_all_change_in_weights = [] #dW

        self.y_pred = 0

    def input_layer(self, input, hidden_layer):
        # input layer to hidden layer
        self.input = np.empty((input, 1), dtype=float)
        self.weights = np.empty((hidden_layer, input))


        self.input_to_hidden = np.dot(self.weights, self.input)
        # self.hidden_layer = self.sigmoid(self.input_to_hidden)
        return self.input_to_hidden
    

    def hidden_layer(self, hidden_layer_, hidden_layer):
        self.hidden = np.empty((hidden_layer, 1))
        self.weights = np.empty((hidden_layer,hidden_layer_))
        print(self.hidden)
        print(self.weights)
        self.summation = np.dot(self.weights, self.hidden)
        return self.summation
    def output(self, hidden_layer, output):
        self.hidden = np.empty((hidden_layer, 1)).transpose()
        self.weights = np.empty((hidden_layer,output))
        print(self.hidden)
        print(self.weights)
        self.summation = np.dot(self.hidden, self.weights)
        return self.summation
    def Relu(self, x):
        return max(0, x)

    


    def backprop(self,x, learning_rate = 0.1, ):
      self.input = x
      self.learning_rate = learning_rate
      # for output to W3
      self.list_of_all_change_in_activations.append((self.list_of_all_activations[-1] - self.y_pred) * self.list_of_all_activations[-1] *(1-self.list_of_all_activations[-1] ) )
      self.list_of_all_change_in_weights.append(self.list_of_all_change_in_activations[0] * self.list_of_all_activations[1])
      ##changing weight 3
      self.list_of_all_weights[2] - self.learning_rate * self.list_of_all_change_in_weights[0]


      # for output to W2
      self.list_of_all_change_in_activations.append(self.list_of_all_weights[2] * self.list_of_all_change_in_activations[-1] * self.Relu(self.list_of_all_weighted_sum[1]))
      self.list_of_all_change_in_weights = self.list_of_all_change_in_activations[1] * self.list_of_all_activations[1]
      self.list_of_all_weights[1] = self.list_of_all_weights[1] - self.list_of_all_change_in_weights[1]



      #for output W1
      self.list_of_all_change_in_activations.append(self.list_of_all_weights[1] * self.list_of_all_change_in_activations[-1] * self.Relu(self.list_of_all_weighted_sum[0]))
      self.list_of_all_change_in_weights = self.list_of_all_change_in_activations[-1] * self.input
      self.list_of_all_weights[0] = learning_rate * self.list_of_all_weights[1] - self.list_of_all_change_in_weights[-1]



      #list of all activations contains activations from the two hidden layers and the activation in the output layer [A1,A2,A3]
      # list of all weights contains all weights which are three [W1, W2, W3]
      # list of all weighted sum contains all weighted sum which are three [Z1, Z2, Z3]

      # list of all change in activations contains all change in activations which are stored like this cause we backpropagate [dZ3, dZ2, dZ1]
      # list of all change in weights contains all change in weights which are stored like this cause we backpropagate [dW3, dW2, dW1] 

      
      

In [9]:
n = NeuralNet()
j = n.output(4,2)
j

[[4.65706588e-310 0.00000000e+000 4.65820104e-310 4.65820102e-310]]
[[6.91157263e-310 6.91157263e-310]
 [6.91157263e-310 6.91157263e-310]
 [6.91156910e-310 6.91156910e-310]
 [6.91156910e-310 6.91156910e-310]]


array([[0., 0.]])

In [9]:
array = np.empty((3,1), int)
array

# mult  = np.array([1,1,1])


array([[94669155195769],
       [             0],
       [            32]])

In [2]:
m =  [ 1,2,3,4,5,6,7,8,9]
m[-7]

3