In [2]:
import numpy as np

### Creating a multilayer perceptron 

In [2]:
a = np.array([[1,1,1,],[1,1,1,],[1,1,1,],[1,1,1,], ])
a

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [6]:
b  = np.array([[1], [1], [1]])
b

array([[1],
       [1],
       [1]])

In [28]:
d = np.random
d

TypeError: 'module' object is not callable

In [14]:
c  = [1,2,3]

d = np.array([c]).transpose()
d

array([[1],
       [2],
       [3]])

class NeuralNet():
    def input_layer(self, units, hidden_layer):
        


In [75]:
class NeuralNet():
    def __init__(self):
        self.list_of_all_weights = [] #W
        self.list_of_all_weighted_sum = [] #Z
        self.list_of_all_activations = [] #A
        self.list_of_all_biases = [] #B

        self.list_of_all_change_in_activations = [] #dZ
        self.list_of_all_change_in_weights = [] #dW
        self.list_of_all_change_in_biases = [] #dB

        self.y_pred = 0

    def input_layer(self, input, hidden_layer, data):
        self.data = data
        if self.list_of_all_weights != []: 
            # input layer to hidden layer
            # self.input = self.list_of_all_activations[0]
            self.weights = self.list_of_all_weights[0]
            self.bias = self.list_of_all_biases[0]
        else:
           
            self.weights = np.ones((hidden_layer, input))
            self.bias = np.ones((hidden_layer,1))

        self.input = np.array([self.data]).transpose()
        #adding weights to list of weights to keep track
        self.list_of_all_weights.append(self.weights)

        self.list_of_all_biases.append(self.bias)


        self.weighted_sum = np.dot(self.weights, self.input) + self.bias

        #keeping track of weighted sum
        self.list_of_all_weighted_sum.append(self.weighted_sum)


        self.activation = self.Relu(self.weighted_sum)

        print(self.weighted_sum)
        #add activation to list to track it
        self.list_of_all_activations.append(self.activation)
        return self.activation
    

    def hidden_layer(self, hidden_layer_, hidden_layer):
        if len(self.list_of_all_weights) == 3: 
            # input layer to hidden layer
            self.hidden = self.list_of_all_activations[0]
            self.weights = self.list_of_all_weights[1]
            self.bias = self.list_of_all_biases[1]
        else:
            self.hidden = np.ones((hidden_layer, 1))
            self.weights = np.ones((hidden_layer,hidden_layer_))
            self.bias = np.ones((hidden_layer_,1))
       
        #adding weights to list of weights to keep track
        self.list_of_all_weights.append(self.weights)

        self.list_of_all_biases.append(self.bias)

        #keeping track of weighted sum
        self.weighted_sum = np.dot(self.weights, self.hidden) + self.bias
        self.list_of_all_weighted_sum.append(self.weighted_sum)



       
        self.activation = self.Relu(self.weighted_sum)

        #add activation to list to track it
        print(self.activation)
        self.list_of_all_activations.append(self.activation)

        return self.activation
    def output(self, hidden_layer, output):
        if len(self.list_of_all_weights) == 3: 
            # input layer to hidden layer
            self.input = self.list_of_all_activations[1]
            self.weights = self.list_of_all_weights[2]
            self.bias = self.list_of_all_biases[2]
        else:
            self.hidden = np.ones((hidden_layer, 1)).transpose()
            self.weights = np.ones((hidden_layer,output))
            self.bias = np.ones((output,1))

        #adding weights to list of weights to keep track
        self.list_of_all_weights.append(self.weights)

        self.list_of_all_biases.append(self.bias)

       
        self.weighted_sum = np.dot(self.hidden, self.weights)
        
       
       
        self.weighted_sum =  self.weighted_sum.transpose()   + self.bias

        # print(self.weighted_sum)
        #keeping track of weighted sum
        self.list_of_all_weighted_sum.append(self.weighted_sum)

    
        self.activation = self.softmax(self.weighted_sum)
    

        
        #add activation to list to track it
        self.list_of_all_activations.append(self.activation)

        # print(self.list_of_all_weights)
        # print(self.list_of_all_activations)
       
        return self.activation
    

    def softmax(self, array):
        exp_output = np.exp(array)
        softmax_probs = exp_output / np.sum(exp_output)
        return softmax_probs

    def Relu(self, array):
        a = []
        for i in array:
            x = max(0, i)
            a.append(x)

        # print(i)
        return np.array(a)
       

    


    def backprop(self,x,y, learning_rate = 0.1, ):
      self.input = x
      self.y = y
      self.learning_rate = learning_rate

      #dc/dz = dc/da * da/dz ------->>>>> -y/a * a*(1-a)
      # for output to W3
      self.list_of_all_change_in_activations.append((-y/self.list_of_all_activations[-1]) * self.list_of_all_activations[-1] *(1-self.list_of_all_activations[-1] ) )
      
      self.list_of_all_change_in_weights.append(self.list_of_all_change_in_activations[-1].dot(self.list_of_all_activations[1].transpose()) )
      self.list_of_all_change_in_biases.append(self.list_of_all_change_in_activations[-1])
      ##changing weight 3
      self.list_of_all_weights[2] = self.list_of_all_weights[2] - self.learning_rate * self.list_of_all_change_in_weights[-1].transpose()
      self.list_of_all_biases[2] = self.list_of_all_biases[2] - self.learning_rate * self.list_of_all_change_in_biases[-1]


      # for output to W2
      
      self.list_of_all_change_in_activations.append((self.list_of_all_weights[2].dot(self.list_of_all_change_in_activations[-1])) * self.Relu(self.list_of_all_weighted_sum[1]))
      self.list_of_all_change_in_weights = self.list_of_all_change_in_activations[1].dot(self.list_of_all_activations[1].transpose())
      self.list_of_all_change_in_biases.append(self.list_of_all_change_in_activations[-1])


      self.list_of_all_weights[1] = self.list_of_all_weights[1] -  self.learning_rate * self.list_of_all_change_in_weights[1]
      self.list_of_all_biases[1] = self.list_of_all_biases[1] - self.learning_rate * self.list_of_all_change_in_biases[-1]



      #for output W1
      self.list_of_all_change_in_activations.append(self.list_of_all_weights[1].transpose().dot(self.list_of_all_change_in_activations[-1]) * self.Relu(self.list_of_all_weighted_sum[0]))
      self.list_of_all_change_in_weights = self.list_of_all_change_in_activations[-1] * self.input
      self.list_of_all_change_in_biases.append(self.list_of_all_change_in_activations[-1])

      self.list_of_all_weights[0] =  self.list_of_all_weights[0] - self.learning_rate *self.list_of_all_change_in_weights[-1]
      self.list_of_all_biases[0] = self.list_of_all_biases[0] - self.learning_rate * self.list_of_all_change_in_biases[-1]



      #list of all activations contains activations from the two hidden layers and the activation in the output layer [A1,A2,A3]
      # list of all weights contains all weights which are three [W1, W2, W3]
      # list of all weighted sum contains all weighted sum which are three [Z1, Z2, Z3]

      # list of all change in activations contains all change in activations which are stored like this cause we backpropagate [dZ3, dZ2, dZ1]
      # list of all change in weights contains all change in weights which are stored like this cause we backpropagate [dW3, dW2, dW1] 

      
      

In [76]:
n = NeuralNet()
z = n.input_layer(3,4, [5,5,5])
y = n.hidden_layer(4,4)
x = n.output(4,2)

j = n.backprop([5,5,5], np.array([[1], [0]]), 0.1 )

[[16.]
 [16.]
 [16.]
 [16.]]
[[5.]
 [5.]
 [5.]
 [5.]]
[[5.]
 [5.]
 [5.]
 [5.]]


In [19]:
a = [1,2,3]

a = np.array([a]).transpose()
a

array([[1],
       [2],
       [3]])

In [2]:
def relu():
    array = np.array([[0], [0]])
    a = []
    for i in array:
        x = max(0, i)
        a.append(x)

        # print(i)
    return   np.array([a]).transpose()


relu()

array([[0],
       [0]])

In [2]:
m =  [ 1,2,3,4,5,6,7,8,9]
m[-7]

3